# Generated by Django 3.2 on 2024-06-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50, verbose_name='Вкус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamKioskIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество мороженого в киоске')),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamkiosk.icecream', verbose_name='Мороженое')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamkiosk.icecreamkiosk', verbose_name='Киоск')),
            ],
        ),
        migrations.AddField(
            model_name='icecreamkiosk',
            name='ice_creams',
            field=models.ManyToManyField(through='icecreamkiosk.IceCreamKioskIceCream', to='icecreamkiosk.IceCream'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('favorite_toy', models.CharField(max_length=50, verbose_name='Любимая игрушка')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='icecreamkiosk.parent', verbose_name='Родитель')),
            ],
        ),
    ]
