# Generated by Django 3.2 on 2024-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icecreamkiosk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50, verbose_name='Тип родства')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamkiosk.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamkiosk.parent')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='icecreamkiosk.ParentChild', to='icecreamkiosk.Child'),
        ),
    ]
